// filter
export const TOGGLE_SECTION = 'TOGGLE_SECTION';

// articles
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const REMOVE_ARTICLE_FROM_READING = 'REMOVE_ARTICLE_FROM_READING';
export const READ_ARTICLE = 'READ_ARTICLE';
export const COUNT_DOWN_ARTICLE = 'COUNT_DOWN_ARTICLE';
export const FINISH_ARTICLE = 'FINISH_ARTICLE';
export const STOP_COUNT_DOWN = 'STOP_COUNT_DOWN';
